# Generated by Django 3.1 on 2020-09-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
