# Generated by Django 3.1 on 2020-09-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200914_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
