# Generated by Django 3.1 on 2020-09-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='username',
        ),
    ]
