# Generated by Django 3.1 on 2020-09-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20200918_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='user',
        ),
    ]
